name: Test

on: [push, pull_request, workflow_dispatch]

jobs:

  test-on-diff-version:
    name: test-diff
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.x']
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate report
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report.html

      - name: Upload code as artifact if tests pass
        if: success() 
        uses: actions/upload-artifact@v2
        with:
          name: source-code
          path: .
